sudo: required
services:
  - docker
before_install:
  - docker pull surendrajat/twrp-builder:latest
before_script:
  - cd $HOME && mkdir twrp
  - wget -q https://or1.androidfilehost.com/dl/jThzOj2E3XnF8TQlzAJk1A/1576579026/1899786940962589838/omni_twrp-5.1.1_cleaned.tar.xz?
    -O $HOME/twrp.tar.xz
  - tar -xJf twrp.tar.xz --directory $HOME/twrp/ && rm twrp.tar.xz
script:
  - cd $HOME/twrp/ && git clone https://github.com/T-rex2017/android_device_Micromax_E453.git device/Micromax/E453
  - git clone https://github.com/TwrpBuilder/android_device_generic_twrpbuilder.git device/generic/twrpbuilder
  - git clone https://github.com/omnirom/android_bootable_recovery.git bootable/recovery --depth=1
  - |
    docker run --rm -i -v "$(pwd):/root/twrp/:rw,z" surendrajat/twrp-builder bash << EOF
    cd /root/twrp/
    source build/envsetup.sh && lunch omni_E453-eng && make -j16 recoveryimage
    exit
    EOF
after_success:
  - export version=$(cat bootable/recovery/variables.h | grep "define TW_MAIN_VERSION_STR" | cut -d '"' -f2)
  - cp $HOME/twrp/out/target/product/E453/recovery.img $HOME/twrp/TWRP-$version-E453-$(date +"%Y%m%d").img
  - curl --upload-file ./$HOME/twrp/TWRP-$version-E453-$(date +"%Y%m%d").img https://transfer.sh/TWRP-$version-E453-$(date +"%Y%m%d").img


